modLoader="javafml" #mandatory
loaderVersion="[24,)" #mandatory
issueTrackerURL="http://github.com/Geforce132/Rologia/issues"
displayURL="https://discord.gg/D8VfMnT"
logoFile="logo.png"
credits="Thanks to all of you guys for your support!"
authors="Geforce"

[[mods]] #mandatory
modId="rologia" #mandatory
version="v0.0.1" #mandatory
displayName="Rologia" #mandatory
description='''
Greek for 'watches', Rologia is a smartwatch mod which adds functional apps and inter-mod support!
''' #mandatory

[[dependencies.rologia]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rologia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"