package net.geforcemods.rologia;

import java.util.Arrays;

import net.geforcemods.rologia.events.RologiaEventHandler;
import net.geforcemods.rologia.gui.GuiHandler;
import net.geforcemods.rologia.item.ItemRologia;
import net.geforcemods.rologia.network.ServerProxy;
import net.geforcemods.rologia.network.packets.PacketCSendRologiaMessage;
import net.geforcemods.rologia.network.packets.PacketSSendRologiaMessage;
import net.geforcemods.rologia.os.apps.App;
import net.geforcemods.rologia.os.apps.events.AppEvent;
import net.geforcemods.rologia.os.resources.ResourceLoader;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.registries.GameData;

@Mod(modid=Rologia.MOD_ID, name=Rologia.MOD_NAME,version=Rologia.VERSION)
public class Rologia {
	
	public static final String MOD_ID = "rologia";
	public static final String MOD_NAME = "Rologia";
	public static final String VERSION = "0.0.1";
	
	@Instance(MOD_ID)
	public static Rologia instance = new Rologia();
	
	@SidedProxy(clientSide = "net.geforcemods.rologia.network.ClientProxy", serverSide = "net.geforcemods.rologia.network.ServerProxy")
	public static ServerProxy serverProxy;

	public static SimpleNetworkWrapper network;
	public static RologiaEventHandler eventHandler = new RologiaEventHandler();
	private GuiHandler guiHandler = new GuiHandler();

	public static Item smartwatch;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList(new String[] {
				"Geforce"
		});
		modMeta.autogenerated = false;
		modMeta.description = "Greek for 'watches', Rologia is a smartwatch mod which adds functional apps and inter-mod support!";
		modMeta.url = "https://discord.gg/D8VfMnT";
		modMeta.logoFile = "/font.png";

		ResourceLoader.MC_DIR = event.getModConfigurationDirectory().getParentFile();
		network = NetworkRegistry.INSTANCE.newSimpleChannel(MOD_ID);
		network.registerMessage(PacketCSendRologiaMessage.Handler.class, PacketCSendRologiaMessage.class, 1, Side.CLIENT);
		network.registerMessage(PacketSSendRologiaMessage.Handler.class, PacketSSendRologiaMessage.class, 2, Side.SERVER);

		smartwatch = new ItemRologia().setCreativeTab(CreativeTabs.REDSTONE).setMaxStackSize(1).setRegistryName("smart_watch").setTranslationKey("rologia:smart_watch");
		GameData.register_impl(smartwatch);
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		NetworkRegistry.INSTANCE.registerGuiHandler(this, guiHandler);

		serverProxy.setupProxy();
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(eventHandler);
	}

	public void postRologiaEvent(AppEvent event) {
		for(App app : serverProxy.getRologiaInstance().getApps()) 
			app.onEventPosted(event);
	}

}
